name: Cypress Tests 
on:
  push:
    branches:

      - 'QA' # Specify the branch name you want to trigger the workflow on
      - 'Integration'
      - 'main'  
jobs:
  build:

    runs-on: 
      labels: ubuntu-latest
    
    strategy:
        matrix:
          browser:
            - chrome 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Cypress Tests in Docker Container
        run: |
          docker build -t my-cypress-image -f Dockerfile --build-arg BROWSER=${{ matrix.browser }} .
          docker run --rm  \
            -v ${{ github.workspace }}/artifacts/screenshots:/Demo1/cypress/screenshots \
            -v ${{ github.workspace }}/artifacts/videos:/Demo1/cypress/videos \
            -v ${{ github.workspace }}/artifacts/reports:/Demo1/cypress/reports my-cypress-image     

      - name: Upload Test Screenshots
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-results-screenshots
          path: ./artifacts/screenshots 

      - name: Upload Test videos 
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
            name: cypress-results-videos

            path: ./artifacts/videos     

      - name: Upload Test result 
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
            name: cypress-results-reports 
            path: ./artifacts/reports
    
      - name: Deploy report page to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./artifacts/reports/